site_name: deployKF
site_description: deployKF builds world-class data and machine learning platforms on any Kubernetes cluster, in any cloud or environment.
site_url: https://www.deploykf.org/

copyright: |-
  © 2024 deployKF Authors | <a class="footer-link" href="/privacy-policy/website/" target="_blank" rel="noopener">Privacy Policy</a>

repo_url: https://github.com/deployKF/deployKF
edit_uri: https://github.com/deployKF/website/edit/main/content
docs_dir: content

nav:
  ## NOTE: navigation is managed by `awesome-pages` plugin, see `.pages` files for configs
  - ...

watch:
  - hooks
  - macros
  - overrides

theme:
  name: material
  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github
  logo: assets/images/logo_1/logo.svg
  logo_banner: assets/images/logo_1/logo_banner.svg
  logo_wide: assets/images/logo_1/logo_wide.svg
  favicon: favicon_1.ico

  features:
    - announce.dismiss
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest

  palette:
    ## Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deploykf-primary
      accent: deploykf-accent
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    ## Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deploykf-primary
      accent: deploykf-accent
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - assets/stylesheets/admonitions.css
  - assets/stylesheets/color.css
  - assets/stylesheets/home.css
  - assets/stylesheets/overrides.css

extra_javascript:
  - assets/javascripts/feedback.js

hooks:
  - hooks/custom_filters.py
  - hooks/external_links_md_extension.py

plugins:
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      exclude:
        - privacy-policy/*
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - assets/stylesheets/admonitions.css
        - assets/stylesheets/color.css
        - assets/stylesheets/home.css
        - assets/stylesheets/overrides.css
      js_files:
        - assets/javascripts/feedback.js
  - redirects:
      redirect_maps:
        'guides/install-deploykf-cli.md': 'guides/deploykf-cli.md'
        'guides/migrate-from-kubeflow-manifests.md': 'guides/kubeflow-distributions.md'
        'guides/tools/external-mysql.md': 'guides/external/mysql.md'
        'guides/tools/external-object-store.md': 'guides/external/object-store.md'
  - search
  - social:
      cards_layout_options:
        color: "#fed1aa"
        background_color: "#294275"
  - table-reader
  ## NOTE: `macros` must be last plugin
  - macros:
      module_name: macros
      include_yaml:
        - latest_deploykf_version: variables/latest_deploykf_version.txt
        - latest_deploykf_cli_version: variables/latest_deploykf_cli_version.txt
      on_error_fail: true
      on_undefined: strict

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

extra:
  analytics:
    ## NOTE: this is commented because we now inject at the CDN level
    #provider: google
    #property: !ENV GA_MEASUREMENT_ID
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Sorry to hear that. 
            Please help us improve by <a href="https://github.com/deployKF/website/issues/new/?title=[Feedback]+{title}" target="_blank" rel="noopener">raising an issue</a>.

  status:
    new: "New Content"

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deployKF/deployKF
      name: deployKF on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/deployKF
      name: deployKF on Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@deployKF
      name: deployKF on YouTube

  generator: false