site_name: deployKF
site_description: deployKF effortlessly integrates Kubeflow and leading MLOps tools on Kubernetes, compose your open ML platform today!
site_url: https://www.deploykf.org/

copyright: "© 2023 deployKF Authors | <a href='/privacy-policy/website/'>Privacy Policy</a>"

repo_url: https://github.com/deployKF/deployKF
edit_uri: https://github.com/deployKF/website/edit/main/content
docs_dir: content

nav:
  ## NOTE: navigation is managed by `awesome-pages` plugin, see `.pages` files for configs
  - ...

theme:
  name: material
  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest

  palette:
    ## Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep-orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    ## Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep-orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - assets/stylesheets/banner.css
  - assets/stylesheets/tables.css

hooks:
  - overrides/custom_filters.py

plugins:
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      exclude:
        - privacy-policy/*
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: false
      js_files: []
      css_files:
        - assets/stylesheets/banner.css
        - assets/stylesheets/home.css
        - assets/stylesheets/tables.css
  - search
  - social
  - table-reader
  ## NOTE: `macros` must be last plugin
  - macros:
      module_name: overrides/custom_macros
      include_yaml:
        - latest_deploykf_version: overrides/variables/latest_deploykf_version.txt
        - latest_deploykf_cli_version: overrides/variables/latest_deploykf_cli_version.txt
      on_error_fail: true
      on_undefined: strict

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: !ENV GA_MEASUREMENT_ID
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Sorry to hear that. 
            Please help us improve by <a href="https://github.com/deployKF/website/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">raising an issue</a>.

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deployKF/deployKF
      name: deployKF on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/deployKF
      name: deployKF on Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@deployKF
      name: deployKF on YouTube
