name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ## all history is needed for `mkdocs-git-revision-date-localized-plugin`
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"

      - run: pip install -r ./requirements.txt

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: mkdocs gh-deploy --force
        env:
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
